# Generated by Django 3.1.6 on 2021-03-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
