# Generated by Django 3.1.6 on 2021-03-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_plant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_plant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
        ),
    ]
