# Generated by Django 3.1.6 on 2021-03-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_post_post_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.post'),
        ),
    ]
