# Generated by Django 3.1.6 on 2021-05-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_emoji',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
