# Generated by Django 3.1.6 on 2021-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20210513_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='celebrating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
