# Generated by Django 3.1.6 on 2021-05-26 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0008_auto_20210519_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('helpful', models.BooleanField(default=False)),
                ('questioned', models.BooleanField(default=False)),
                ('celebrated', models.BooleanField(default=False)),
                ('responsePost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.post')),
                ('responseUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
